/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	operatorsv1 "github.com/operator-framework/operator-marketplace/pkg/apis/operators/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOperatorSources implements OperatorSourceInterface
type FakeOperatorSources struct {
	Fake *FakeOperatorsV1
	ns   string
}

var operatorsourcesResource = schema.GroupVersionResource{Group: "operators.coreos.com", Version: "v1", Resource: "operatorsources"}

var operatorsourcesKind = schema.GroupVersionKind{Group: "operators.coreos.com", Version: "v1", Kind: "OperatorSource"}

// Get takes name of the operatorSource, and returns the corresponding operatorSource object, and an error if there is any.
func (c *FakeOperatorSources) Get(name string, options v1.GetOptions) (result *operatorsv1.OperatorSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(operatorsourcesResource, c.ns, name), &operatorsv1.OperatorSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorsv1.OperatorSource), err
}

// List takes label and field selectors, and returns the list of OperatorSources that match those selectors.
func (c *FakeOperatorSources) List(opts v1.ListOptions) (result *operatorsv1.OperatorSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(operatorsourcesResource, operatorsourcesKind, c.ns, opts), &operatorsv1.OperatorSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &operatorsv1.OperatorSourceList{ListMeta: obj.(*operatorsv1.OperatorSourceList).ListMeta}
	for _, item := range obj.(*operatorsv1.OperatorSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested operatorSources.
func (c *FakeOperatorSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(operatorsourcesResource, c.ns, opts))

}

// Create takes the representation of a operatorSource and creates it.  Returns the server's representation of the operatorSource, and an error, if there is any.
func (c *FakeOperatorSources) Create(operatorSource *operatorsv1.OperatorSource) (result *operatorsv1.OperatorSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(operatorsourcesResource, c.ns, operatorSource), &operatorsv1.OperatorSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorsv1.OperatorSource), err
}

// Update takes the representation of a operatorSource and updates it. Returns the server's representation of the operatorSource, and an error, if there is any.
func (c *FakeOperatorSources) Update(operatorSource *operatorsv1.OperatorSource) (result *operatorsv1.OperatorSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(operatorsourcesResource, c.ns, operatorSource), &operatorsv1.OperatorSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorsv1.OperatorSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOperatorSources) UpdateStatus(operatorSource *operatorsv1.OperatorSource) (*operatorsv1.OperatorSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(operatorsourcesResource, "status", c.ns, operatorSource), &operatorsv1.OperatorSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorsv1.OperatorSource), err
}

// Delete takes name of the operatorSource and deletes it. Returns an error if one occurs.
func (c *FakeOperatorSources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(operatorsourcesResource, c.ns, name), &operatorsv1.OperatorSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOperatorSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(operatorsourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &operatorsv1.OperatorSourceList{})
	return err
}

// Patch applies the patch and returns the patched operatorSource.
func (c *FakeOperatorSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *operatorsv1.OperatorSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(operatorsourcesResource, c.ns, name, pt, data, subresources...), &operatorsv1.OperatorSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorsv1.OperatorSource), err
}
